name: Build and run functional tests using ragger through reusable workflow

# This workflow will build the app and then run functional tests using the Ragger framework upon Speculos emulation.
# It calls a reusable workflow developed by Ledger's internal developer team to build the application and upload the
# resulting binaries.
# It then calls another reusable workflow to run the Ragger tests on the compiled application binary.
#
# The build part of this workflow is mandatory, this ensures that the app will be deployable in the Ledger App Store.
# While the test part of this workflow is optional, having functional testing on your application is mandatory and this workflow and
# tooling environment is meant to be easy to use and adapt after forking your application

on:
  workflow_dispatch:
    inputs:
      golden_run:
        type: choice
        required: true
        default: 'Raise an error (default)'
        description: CI behavior if the test snapshots are different than expected.
        options:
          - 'Raise an error (default)'
          - 'Open a PR'
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  build_application_testnet:
    name: Build application using the reusable workflow for testnet
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      upload_app_binaries_artifact: "compiled_app_binaries_testnet"

  ragger_tests_testnet:
    name: Run ragger tests using the reusable workflow for testnet
    needs: build_application_testnet
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_ragger_tests.yml@v1
    with:
      download_app_binaries_artifact: "compiled_app_binaries_testnet"
      regenerate_snapshots: ${{ inputs.golden_run == 'Open a PR' }}

  build_application_mainnet:
    name: Build application using the reusable workflow for mainnet
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      upload_app_binaries_artifact: "compiled_app_binaries_mainnet"
      flags: "COIN=BBNST"

  ragger_tests_mainnet:
    name: Run ragger tests using the reusable workflow for mainnet
    needs: build_application_mainnet
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_ragger_tests.yml@v1
    with:
      download_app_binaries_artifact: "compiled_app_binaries_mainnet"
      test_filter: "test_dashboard"
      test_options: "--network main"
      regenerate_snapshots: ${{ inputs.golden_run == 'Open a PR' }}
